name: My workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-lastest

    steps:
      - name: hello world
        run: echo "Hello, world!"

